operator:
  image: null
  reconcileIntervalSeconds: 60
sqlServer:
  image: null
  instances:
    - name: nonproduction
      memory: 2Gi
      timezone: UTC
      storage:
        size: 500Gi
        class: default
      passwords:
        externalSecret:
          path: secret/sqlserver
      backups:
        azureBlobStorage:
          externalSecret:
            path: secret/sqlbackups
      scheduling:
        environment: nonproduction