operator:
  image: null
  reconcileIntervalSeconds: 60
sqlServer:
  image: null
  instances:
    - name: nonproduction
      memory: 2Gi
      password: Passw0rd!
      timezone: UTC
      ports:
        first: 1435
        last: 1450
      storage:
        size: 500Gi
        class: default
      backups:
        azureBlobStorage:
          externalSecret:
            path: secret/sqlbackups
