{{ range $i, $instance := $.Values.sqlServer.instances }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-{{ $instance.name }}
  labels:
    app: k8s-managed-sql
    role: operator
    instance: {{ $instance.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: k8s-managed-sql
      role: operator
      instance: {{ $instance.name }}
  template:
    metadata:
      labels:
        app: k8s-managed-sql
        role: operator
        instance: {{ $instance.name }}
    spec:
      volumes:
      containers:
      - image: {{ $.Values.operator.image }}
        name: operator
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_NAME
          value: {{ $instance.name | quote }}
        - name: NAMESPACE
          value: {{ $.Release.Namespace | quote }}
        - name: RECONCILE_INTERVAL_SECONDS
          value: {{ $.Values.operator.reconcileIntervalSeconds | quote }}
        - name: BACKUPS_AZURE_BLOB_CONTAINER_URL
          valueFrom:
            secretKeyRef:
              name: {{ $instance.name }}-backups-azure-blob-storage-external-secret
              key: AZURE_BLOB_CONTAINER_URL
        - name: BACKUPS_AZURE_BLOB_CONTAINER_SAS
          valueFrom:
            secretKeyRef:
              name: {{ $instance.name }}-backups-azure-blob-storage-external-secret
              key: AZURE_BLOB_CONTAINER_SAS
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $instance.name }}-passwords
              key: SA_PASSWORD
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $instance.name }}-backups-azure-blob-storage-external-secret
spec:
  backendType: vault
  data:
    - key: {{ $instance.backups.azureBlobStorage.externalSecret.path }}
      property: AZURE_BLOB_CONTAINER_URL
      name: AZURE_BLOB_CONTAINER_URL
    - key: {{ $instance.backups.azureBlobStorage.externalSecret.path }}
      property: AZURE_BLOB_CONTAINER_SAS
      name: AZURE_BLOB_CONTAINER_SAS
  kvVersion: 1
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $instance.name }}-passwords
spec:
  backendType: vault
  data:
    - key: {{ $instance.passwords.externalSecret.path }}
      property: SA_PASSWORD
      name: SA_PASSWORD
  kvVersion: 1
{{ end }}