kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-full-access
rules:
- apiGroups: [""]
  resources: ["services", "secrets"]
  verbs: ["*"]
- apiGroups: ["managedsql.api.k8s.dma.net.nz"]
  resources: ["sqldbs"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-full-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-full-access
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: default
