apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sqldbs.managedsql.api.k8s.dma.net.nz
spec:
  group: managedsql.api.k8s.dma.net.nz
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                instance:
                  type: string
      additionalPrinterColumns:
  scope: Namespaced
  names:
    plural: sqldbs
    singular: sqldb
    kind: SQLDB
